### ISSUE TITLE
Setup initial project structure

### ISSUE THREAD

**Issue by danixeee** [textX/textX-LS#1]
- [x] Implement dummy language server (based on _[pygls](https://github.com/openlawlibrary/pygls)_)
- [x] Implement VS Code client extension
- [ ] Add CHANGELOG.md
- [ ] Update README.md

**Comment by danixeee** [comment]
The initial idea is to create a two distinct python packages inside this repo:

- _textX-LS-core_ package will contain a logic for features like _code completion_, _go to definition_, _find all references_, etc..

- _textX-LS_ will be a thin layer around _core_ package and provide those features over _Language Server Protocol_

This way we will be able to use _core_ package for other tools in the future, without installing unnecessary libraries.

I am still unclear if we want to share the same _CHANGELOG_ for both packages, thoughts?

**Comment by igordejanovic** [comment]
Since those two will be packaged independently, they will have different version numbers etc., I think it is better to maintain two separate changelogs. My guess is that would be less confusing.
