### ISSUE TITLE
Install new languages as python packages

### ISSUE THREAD

**Issue by danixeee** [textX/textX-LS#12]
Languages are loaded from entry points, so I will implement mechanism which will allow to add custom languages to the extension by installing/loading them as python packages.

We will have commands like:
- install
- uninstall
- list languages

We will use a [language template](https://github.com/textX/textX-LS/blob/master/textX-LS/core/textx_ls_core/languages/__init__.py), so creating new language support should be straightforward.

- [x] Manual install and make it work with core CLI
- [x] New language project scaffolding (server + CLI)
- [x] [server] Install language package from path (setup.py location)
- [x] [server] Uninstall lang package
- [x] [server] List lang packages (CLI supports it)
- [ ] [server] Modify manifest `package.json` file (add coloring, add activation event, ...)
- [ ] [server] Install from PyPI (low priority)
- [ ] Add tests

Most of those commands could be implemented on client-side but I want to move as much logic as possible to LS.

**Comment by danixeee** [comment]
Since loading a meta-model became more complex I have implemented a mechanism which, following the predefined [language template](https://github.com/textX/textX-LS/blob/danixeee/language-installation-mechanism/textX-LS/core/textx_ls_core/languages/__init__.py), allows us to create languages as python packages and install them as plugins.
This way we will be able to register custom commands, coloring, code completions, etc and distribute those packages (PyPI, ...).

For now we have (still WIP; see _gif_ bellow):
- scaffolding
- installing
- uninstalling language

There are[ built-in languages ](https://github.com/textX/textX-LS/tree/master/textX-LS/core/textx_ls_core/languages) which cannot be uninstalled. 

![textx-ls](https://user-images.githubusercontent.com/16227576/54218353-b4a28b00-44ed-11e9-8b14-d4592ce03e1a.gif)

The only problem for now is that after installing language package, we need to change [extension metadata](https://github.com/textX/textX-LS/blob/master/client/package.json) (not yet implemented) and after this, VS Code has to be restarted.

@igordejanovic @goto40 What do you think about this approach?

**Comment by goto40** [comment]
Hi. Sounds very interesting. Give me some days to have a look.

**Comment by goto40** [comment]
Hi!

I would like to know if you need the grammar? Or is the metamodel instance (python object) enough?

I ask, because I do not understand why a standard template must be used to create a language. *If the metamodel object is enough*, ... 
 * ...we just need to **specify a factory function** to create or get the metamodel object.
 * Also, in case of **multi metamodels**, editor support for associated languages (used by the main DSL) comes for free...

*If you need data derived from the grammar*: 
 * Is it also valid that the metamodel **(DSL) package yields the relevant editor support objects**, instead that the editor module accesses the grammar directly.
 * This will also simplify **multi metamodel handling**. We can **delegate the editor support object generation to the associated DLS modules** (even when we have no direct grammar access).

I will be happy to discuss... For sure I also did not fully understand all details you designed (which - for sure - are very good for the use case you implemented).

**I sum**, I try to find a way, were the **responsibility of creating editor support objects** is moved into the language DSL module. 
 * I think this simplifies multi metamodel support (see above)
 * I also think this simplifies configuration overhead (you just need to *find or specify a python module*, where the relevant factory functions are found.

**Comment by danixeee** [comment]
Hi @goto40, thanks for spending some time on this.

I think we are sharing the same idea, maybe I just haven't explained it well.

So, _language template_ that I mentioned, is actually _language support template_ that _language server_ knows how to interpret, to provide different capabilities for language that we are targeting.

> I would like to know if you need the grammar? Or is the metamodel instance (python object) enough?

Currently I am not dealing with grammar, I just need metamodel as python object.

Lets look at example of template for language support:

```
class MyLanguageSupport(LanguageTemplate):

    @property
    def extensions(self) -> List[str]:
        """Files with these extensions tells me which language template I should use."""
        return ['ext1', 'ext2']

    @property
    def language_name(self) -> str:
        """ ... """
        pass

    @property
    def metamodel(self) -> TextXMetaModel:
       """Load metamodel and return me a python object."""

    def rule_completions(self):
        """Not supported for now, but the idea is customize code completion for
        given rule.
        """
        return {
            'SomeRuleID': # don't know yet:)
        }

    def outline(self):
        """ Tells me what to display in outline tree """
        pass

    def syntax_highlighting(self):
        pass
```

This is the flow (using VS Code for e.g.):
1. Install textX extension
    - several builtin languages are supported (textX, outline, etc.)
2. Scaffold a template to support new language
    - this is just to reduce errors with boilerplate code and speed up development
3. Customize template
    - required properties are: metamodel, language name and file extensions
4. Install template
    - from package location
    - from PyPI
    - in editable mode (optional)
5. Open file with specified extension

If user triggers for e.g. _code completions_ we will execute our logic to get completion items, but we will also check if language template has its own rules that will modify the result.

Benefits that I see:

- server does not need to know how to load a metamodel
- python everywhere (no need to learn any configuration, less documentation, ...)
- easily customizable

Note that all of these stuff are implemented in `textX-LS-core` package and available with `CLI`:

![image](https://user-images.githubusercontent.com/16227576/54324636-c6c01e80-45fe-11e9-8b66-039ee7afd7c0.png)

It would be very helpful if we can create an example DSL which can be used to test multi-metamodels, scoping and everything that is supported in current textX metamodel.

**Comment by goto40** [comment]
Great. I could create an example of some dsls with different features the next 7-14 days... ?

**Comment by danixeee** [comment]
That would be great, thank you. Also, I think more examples should be added to the _textX_ repo, specially those that are showing how to use _scoping_ and _multi-metamodels_. I had to go through some tests to see how that's working and I am still not familiar with it.

**Comment by igordejanovic** [comment]
@danixeee I really like where this is heading to.

So, if I understand the idea, using LSP custom commands we should be able to cover language feature that are not available in the current LSP spec, like outline and coloring, and then switch to official support once they are available?

**Comment by danixeee** [comment]
@igordejanovic in general we will be able to do that, but I meant something else.

For instance, we create a language for entity modeling and several code generators and package all that into a python package (which follows our language template from above). I thought it would be handy for someone to use those generators directly from VS Code UI, like Docker commands:

![image](https://user-images.githubusercontent.com/16227576/54498598-b4e5c080-4909-11e9-818d-22ddd8c661b5.png)

Regarding outline and coloring:

Old textX language server has _coloring_ and _outline_ DSLs which allows us to specify how our language syntax will be highlighted and what will be displayed in the outline tree.
We are still going to use these DSLs, but LSP started supporting [outline tree](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol) and I hope it will make our implementation easier. So, following the language template, we can maybe return an _outline_ model as a string, to tell _textX-LS_ how to display a tree:

```
class MyLanguageSupport(LanguageTemplate):

    def outline(self):
        """ Tells me what to display in outline tree """
        return pathlib.Path('./outline.txol').read_text()
```

Static syntax highlighting is a problem, because it is provided as a JSON file and that file is linked in a [package.json](https://github.com/textX/textX-vscode/blob/master/package.json#L65) (extension manifest file). Every change in manifest file requires VS Code to be restarted (in order to see those changes).
We didn't have this problem with the old extension, because we were generating a new extension (for each new DSL) which needed to be installed.

Semantic highlighting will be supported in the near future, AFAIK.

**Comment by igordejanovic** [comment]
Calling generators from VS UI would be handy indeed. It would also be nice to be able to register code generators using extension point, like it is done for languages. In that way, generators would be discovered dynamically. We could still pack generators together with languages (in the same Python package), but we would also enable other developers to write generators for existing languages and deploy to PyPI as a separate Python packages. That would enable the development of generators for various target stacks, done by different developers, based on pre-existing languages.

For outline, I agree, language designer could supply `.txol` file from `LanguageTemplate` inherited class and textx-LS could interpret that file and provide responses for [Document Symbols Request](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol) calls.

For highlighting we might provide a generator for VS Code JSON file using the old coloring spec (IIRC we had a DSL for coloring description before)? The need to restart VS Code is PITA but that is what we can do at the moment. The highlighting spec generators could be provided for other editors as well, as a separately installable Python packages. And those generators could be registered the same way generators for other languages are registered (using the same extension point).

**Comment by danixeee** [comment]
> Calling generators from VS UI would be handy indeed. It would also be nice to be able to register code generators using extension point, like it is done for languages. In that way, generators would be discovered dynamically. We could still pack generators together with languages (in the same Python package), but we would also enable other developers to write generators for existing languages and deploy to PyPI as a separate Python packages. That would enable the development of generators for various target stacks, done by different developers, based on pre-existing languages.

I like the idea and I have also thought about that. At this point I am not sure about implementation details, but I guess we will need to dynamically register commands using LSP [register capability](https://microsoft.github.io/language-server-protocol/specification#client_registerCapability) method and support this in `pygls`.

> For highlighting we might provide a generator for VS Code JSON file using the old coloring spec (IIRC we had a DSL for coloring description before)?

Yes, we will reuse existing DSL, but its interpreter will require some refactoring.

> The need to restart VS Code is PITA but that is what we can do at the moment. The highlighting spec generators could be provided for other editors as well, as a separately installable Python packages. And those generators could be registered the same way generators for other languages are registered (using the same extension point).

VS Code dev team recently implemented [extension installation without reloading](https://code.visualstudio.com/updates/v1_31#_no-reload-on-install). Also, we have VS Code [CLI](https://stackoverflow.com/a/34339780).

Workaround that came to my mind yesterday:

- generate a small `.vsix` file which will contain only coloring file, snippets and activation events on provided file extensions
- install `.vsix` file with vscode CLI command (I hope reloading won't be required)
- Activate function of this extension will activate textX extension (if not activated already)
    Simple as:
    ```typescript
    export async function activate(context: ExtensionContext) {
       const textxExtension = extensions.getExtension("textX.textX");
       if (textxExtension && !textxExtension.isActive) { textxExtension.activate(); }
    }
    ```

It's far from perfect, but should do the job for now. :) I will eventually ask them if they plan to support dynamically editing of metadata file.

P.S. Development is not going very fast because I am not merging PRs without proper tests, but I am planning a release to _marketplace_ as soon as I finish with basic language management feature (installing, uninstalling, ...) and language validation.

**Comment by igordejanovic** [comment]
Sounds great! 
BTW, the project is developing at just the right pace. I'm always for a piece of well tested/documented code than for a bunch of untested/undocumented. :)

**Comment by danixeee** [comment]
@igordejanovic Sadly, VS Code window needs to be restarted in order to extension take an effect if it is installed via _cli_. I have created the [issue](https://github.com/Microsoft/vscode/issues/71491) to see if there are some other ways to do this, or if it is possible to implement it.

**Comment by danixeee** [comment]
Closing in favour of #13.
