### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by danixeee** [textX/textX-LS#2]
Enable and setup travis CI/CD.

- Regular builds should upload the extension artifact with following format `textX-LS-{VERSION}+{BUILD_NUMBER}.vsix`
- Merge to master should upload the extension artifact with format `textX-LS-{VERSION}.vsix`
- After pushing the tag to master, python packages should be uploaded to PyPI and extension should be uploaded to the [marketplace](https://marketplace.visualstudio.com)

**Comment by danixeee** [comment]
@igordejanovic  Since we have two distinct python packages with different version numbers, how we are going to tag the master branch? Should we automatically trigger package and extension upload to the PyPI and marketplace or we just want to automatize deployment for textX extension and manually upload textX-LS-core if needed?

**Comment by igordejanovic** [comment]
>  Since we have two distinct python packages with different version numbers, how we are going to tag the master branch? Should we automatically trigger package and extension upload to the PyPI and marketplace or we just want to automatize deployment for textX extension and manually upload textX-LS-core if needed?

If we could automate both deployments it would be nice. It seem reasonable to me to sync versions of LS-core and LS-server to make things simpler. What we could do is to use tag prefixes for LS-core/server (e.g. `ls-1.0`) and VS Code(e.g. `code-1.0`) when tagging new versions. Not sure if that could lead to problems in Travis CI/CD automation.

> Language server can be installed/updated directly from PyPI when extension gets activated, so we don't have to update VS Code extension version in that case (same will apply for other clients in the future).

That sounds good.

**Comment by igordejanovic** [comment]
I was thinking about my proposal to use a single version for both `core` and `server`. Not sure that would be a good idea as we might end up with dummy version increase. When e.g. `core` change and `server` remains the same we would nevertheless have to move `server` version as well which would be confusing.
I guess it would be better to stick with a separate version for each package.

**Comment by danixeee** [comment]
I am playing with Azure DevOps there days and I will try to setup CI/CD there. 

So far I accomplished following: 

**Continuous Integration**

CI builds and tests code on _macOS_, _Ubuntu_ and _Windows_ platforms and with _3.5+_ python versions.

CI triggers on:
- each push to any branch
- pull-requests

CI steps:

<img src="https://user-images.githubusercontent.com/16227576/51062847-b7215b00-15f8-11e9-8e37-b4f88bd72d35.png" height="400px">

What is left on successful builds:

Creating following artifacts:
- _textX-LS-core_ wheel
- _textX-LS-server_ wheel
- VS Code extension file (.vsix)

I have to see how we will install _textX_ language server inside our VS Code extension. For now, I will probably add some logic to install those packages from `.whl` which will be packaged in the `.vsix` as well.
So, when VS Code extension is installed we will:

- Create _virtualenv_ inside the extension folder with user's preinstalled python 3.5+
- Navigate to directory with _textX-LS-core_ and _textX-LS-server_
- Install those packages
- Activate the extension

This way we will be sure that every created VS Code extension artifact will use the python packages from the same build.

**Continuous Delivery**

CD should happen on master's branch tags.

As you suggested, we can have a prefix for tags for each project inside this repo:

- `core-0.1.0`
- `ls-0.3.0`
- `code-1.2.3`

Different tag prefixes should trigger different deployment scripts.
