### ISSUE TITLE
Language server: how does it work?

### ISSUE THREAD

**Issue by alessiostalla** [textX/textX-LS#35]
Greetings,

I'm evaluating textX-LS in VSCode to write a tutorial on it. I've followed the installation procedure in the README and I get syntax highlighting for sample languages. However, I don't think the language server is working, or I don't understand how it's supposed to work.
I'm launching the Server+Client, opening a file (say, program.rbt for the robot language), hitting Ctrl+Space, and expecting to get suggestions according to the language. However, only standard suggestions based on the textual content of the file pop up.

**Comment by danixeee** [comment]
Hello, it's great to see that you are interested in writing a tutorial for _textX-LS_.

[Here](https://github.com/textX/textX-LS#features) you can see what features are currently supported and sadly code completions (suggestions) are not yet implemented. We are currently focused on language management (installing / uninstalling textX languages) and configuring and running generators within the extension.

**Comment by alessiostalla** [comment]
Hello,
thanks for your kind reply. I've missed that code completion is not yet implemented, I got fooled by the mention of a language server component.
Anyway, I'll let you know when the tutorial is ready if you wish. If you want to close this issue it's fine by me – I'm letting it open as maybe someone else might see it.

**Comment by alessiostalla** [comment]
Here it is: https://tomassetti.me/quick-domain-specific-languages-in-python-with-textx/
I hope it will be useful to somebody.
I'm closing this issue as I got an answer already. Keep up with the good work!

**Comment by igordejanovic** [comment]
@alessiostalla WOW! Looks great, thanks! Will add it to the textX docs.

Here are some corrections:

1.  > The initial rm is necessary, as textX doesn’t overwrite a dot file if it
    > already exists, for some reason.
    
    -   `generate` sub-command doesn't overwrite by default to prevent accidental
        errors but if you want to always overwrite use `--overwrite` switch in
        the generate command.
2.  > Just like in other rules, we’ve defined a precise ordering of the
    > constituents of each expression/declaration; here, for example, the line
    > color must come before the fill color. TextX is not very well suited to
    > grammars that admit a free ordering of expressions.
    > 
    > &#x2026; 
    > 
    > TextX is a good choice when the speed of development and the integration
    > with Python are key concerns, and when the language is close enough to what
    > textX supports best: a regular, ordered and deterministic structure, where
    > whitespace is not significant. This can cover a wide range of languages, for
    > data definition, configuration, etc. However, more free-form languages, such
    > as most programming languages (domain-specific or general-purpose), probably
    > aren’t a good target for textX.
    
    -   There is an unordered group repetition operator <http://textx.github.io/textX/stable/grammar/#repetitions>
    -   If you want your color statements to be in arbitrary order you can wrap
        the sub-expression in a parentheses with `#` operator:
        
            Shape:
            'shape' name=ID
               (line_color=LineColor?
                fill_color=FillColor?)#
               lines+=Line
            'end'
            ;
    -   Not sure if that fully covers the remark in the conclusion section.
        Will be glad to discuss :)
3.  > In practice, textX does a limited form of symbol resolution for us. 
    
    -   This is just a default symbol name resolution. But, if needed there is
        a support for a [fully elaborate and arbitrary complex resolution strategies](http://textx.github.io/textX/stable/scoping/)

4.  > Next, we’re going to write a package descriptor for Turtle, which is a
    > bit of a tedious process. We can use the following as a template:
    
    -   This is correct for the current stable version. But there is a
        [`startproject` command in the dev version](https://github.com/textX/textX/pull/234) that will make starting a new
        language project **much** easier.

**Comment by igordejanovic** [comment]
Here is a better link for the project scaffolding in the dev version http://textx.github.io/textX/latest/scaffolding/

**Comment by alessiostalla** [comment]
@igordejanovic many thanks for your suggestions, I'll incorporate those :)

**Comment by igordejanovic** [comment]
@alessiostalla Great! Thanks a lot for the tutorial.

**Comment by danixeee** [comment]
@alessiostalla Really great tutorial, thank you! I am glad that you successfully setup textX-LS! :)

Few more words, not much related to the tutorial:

When language is installed in editable mode, language server finds language keywords from the grammar and the VS Code client paints those keywords in the model. In that case, syntax coloring is not perfect, but is automatically updated as you update the grammar.

Once language project is ready, we create python package and _vsix_ package which contains _textmate_ file with all the keywords. Our packaged extension requires _textX_ extension to work properly, since only _textX_ extension knows how to communicate with the language-server.

There is a model and a meta-model validation inside VS Code, as well.

**Comment by alessiostalla** [comment]
@igordejanovic @danixeee thanks a lot for your comments! I've incorporated some of them in the article clarifying it a bit.
