### ISSUE TITLE
Could the version range of the click dependency be expanded?

### ISSUE THREAD

**Issue by ryansobol** [textX/textX-LS#38]
So, I'm getting the following error when attempting to add `click` as a dependency to my project, which also depends on ` textx-ls-core`.

```
$ poetry add click
Using version ^7.1.2 for click

Updating dependencies
Resolving dependencies... (0.1s)

[SolverProblemError]
Because textx-ls-core (0.1.1) depends on click (7.0)
 and no versions of textx-ls-core match >0.1.1,<0.2.0, textx-ls-core (>=0.1.1,<0.2.0) requires click (7.0).
So, because tsdoc depends on both textx_ls_core (^0.1.1) and click (^7.1.2), version solving failed.
```

Could the version range of the click dependency be expanded?

https://github.com/textX/textX-LS/blob/master/textX-LS/core/setup.py#L53

Maybe to `click>=7.0`? Or to `click>=7.0,<8.0`? Thank you!

**Comment by danixeee** [comment]
I have removed `click` dependency for now, it's on the _master_ branch.
